# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.PositiveSmallIntegerField(choices=[(1, 'venda'), (2, 'aluguel')])),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição-do-Imovel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Imovel',
                'ordering': ['name'],
            },
        ),
    ]
