# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['-created'], 'verbose_name': 'Imovel'},
        ),
        migrations.AlterField(
            model_name='imovel',
            name='book_type',
            field=models.PositiveSmallIntegerField(choices=[('venda', 'venda'), ('aluguel', 'aluguel')]),
        ),
    ]
