# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_auto_20170213_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='book_type',
            field=models.PositiveSmallIntegerField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')]),
        ),
    ]
