# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0004_auto_20170214_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cumuruxatiba/images', verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.Imovel', verbose_name='Categoria')),
            ],
        ),
    ]
